### ISSUE TITLE
scp broken

### ISSUE THREAD

**Issue by beeso018** [UMN-EGGL/MSI-Setup#5]
So, I can't scp anything from MSI to a different computer because of this new profile thing. I get the following error:

```
x-10-0-0-241:~ skbeeson$ scp beesons@login.msi.umn.edu:~/Ne/cosi-2.0/all_sims.txt ./
beesons@login.msi.umn.edu's password: 
protocol error: unexpected <newline>
```

From what I've googled, it seems like the problem is the use of echo. When I comment out the `source /home/mccuem/shared/MSI-Setup/mccuem_profile` from my .bashrc, scp works again.

**Comment by schae234** [comment]
Should be fixed in 2d241fff36d53f091

You were right about the problem. `scp` isn't an interactive shell so some of the code in the profile breaks it. I now check it per [this response in stack overflow](http://unix.stackexchange.com/questions/18231/scp-fails-without-error)

Should be fixed and live on MSI now!
